server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pinterest_clone
    username: pinuser
    password: pinuser
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 9385601e4a0d12837f53
            clientSecret: 1973b7388045a911717785b15b365c8ab0d19e71
            accessTokenUri: https://github.com/login/oauth/access_token
            userAuthorizationUri: https://github.com/login/oauth/authorize
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
          resource:
            userInfoUri: https://api.github.com/user

